@url_catalogo = http://localhost:8081
@id = 1

### Obtener Categoría por ID
# @name ObtenerCategoriaPorID
GET {{url_catalogo}}/api/categorias/{{id}}

> {%
    client.test("Status 200 OK", function() {
        client.assert(response.status === 200, "El estado de respuesta no es 200");
    });
    client.test("Response tiene ID", function() {
        client.assert(response.body.hasOwnProperty('id'), "La respuesta no tiene la propiedad 'id'");
    });
%}