# 1. IDENTIFICACIÓN
spring.application.name=ecomarket
server.port=8084

# 2. CLIENTE FEIGN 
catalogo.service.url=localhost:8081

# 3. BASE DE DATOS (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/carrito_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true