# Nombre de la aplicación
spring.application.name=ecomarket-descuento

# Puerto del servidor (distinto a pedidos y reseñas)
server.port=8086

# Configuración de Base de Datos (MySQL)
# Asegúrate de crear la base de datos 'ecomarket_descuentos_db' en tu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/descuentos_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect