spring.application.name=ecomarket

# Configuración del Servidor
server.port=8083

# Configuración de la Base de Datos (Ajusta el nombre de la DB)
spring.datasource.url=jdbc:mysql://localhost:3306/resenas_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URLs de Microservicios (Para el WebClient que configuramos antes)
pedidos.service.url=localhost:8081
usuarios.service.url=localhost:8080